[book]
title = "UniBook"
authors = ["pkeugine"]
description = "The true basics of programming"
language = "en"
multilingual = false
src = "src"

[rust]

[build]

[preprocessor.index]

[preprocessor.links]

[output.html]

[output.html.search]